# docker-compose.yml
version: '3.8'
services:
  counter-agent:
    build: ./services/counter-agent
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LC_MODEL=${LC_MODEL}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./services/counter-agent:/app
    
  waha-integrator:
    build: ./services/waha-integrator
    ports:
      - "8001:8001"
    environment:
      - AGENT_BASE_URL=http://agent:8000
      - WAHA_BASE_URL=${WAHA_BASE_URL}
      - WAHA_API_KEY=${WAHA_API_KEY}
    depends_on:
      - counter-agent
    volumes:
      - ./services/waha-integrator:/app