name: build-and-deploy

on:
  push:
    branches: [main]
    paths:
      - 'services/lyra/**'
      - '.github/workflows/lyra-cicd.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'services/lyra/**'
      - '.github/workflows/lyra-cicd.yaml'

env:
  registry: ghcr.io
  username: ${{ github.repository_owner }}
  password: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/lyra

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to registry
        run: echo "${{ env.password }}" | docker login ${{ env.registry }} -u ${{ env.username }} --password-stdin

      - name: Build
        run: |
          cd services/lyra
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

      - name: Debug owner
        run: echo "Repository owner is ${{ github.repository_owner }}"

      - name: Push
        run: |
          cd services/lyra
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest